// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAISeW4S0-iz1x8Crc3OLuvSfCz_nQzVhs',
    appId: '1:512034762489:web:fd276fb4a937e162917c28',
    messagingSenderId: '512034762489',
    projectId: 'reddit-clone-b5636',
    authDomain: 'reddit-clone-b5636.firebaseapp.com',
    storageBucket: 'reddit-clone-b5636.firebasestorage.app',
    measurementId: 'G-99KQWBBYYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-DCeiqVPA90UP1llCG_bJCkKfFv8eOEA',
    appId: '1:512034762489:android:434b7491e4585351917c28',
    messagingSenderId: '512034762489',
    projectId: 'reddit-clone-b5636',
    storageBucket: 'reddit-clone-b5636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8xgBo4IszdtwtNF074omZZxjX6-v0pBg',
    appId: '1:512034762489:ios:e4577344bb0d3ef6917c28',
    messagingSenderId: '512034762489',
    projectId: 'reddit-clone-b5636',
    storageBucket: 'reddit-clone-b5636.firebasestorage.app',
    androidClientId: '512034762489-clumo004g56rjs68f4b5m7ek3825hpmb.apps.googleusercontent.com',
    iosClientId: '512034762489-5q2gukf988bm7th5nobch52qsprp125b.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8xgBo4IszdtwtNF074omZZxjX6-v0pBg',
    appId: '1:512034762489:ios:e4577344bb0d3ef6917c28',
    messagingSenderId: '512034762489',
    projectId: 'reddit-clone-b5636',
    storageBucket: 'reddit-clone-b5636.firebasestorage.app',
    androidClientId: '512034762489-clumo004g56rjs68f4b5m7ek3825hpmb.apps.googleusercontent.com',
    iosClientId: '512034762489-5q2gukf988bm7th5nobch52qsprp125b.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAISeW4S0-iz1x8Crc3OLuvSfCz_nQzVhs',
    appId: '1:512034762489:web:6699965ec49ba46e917c28',
    messagingSenderId: '512034762489',
    projectId: 'reddit-clone-b5636',
    authDomain: 'reddit-clone-b5636.firebaseapp.com',
    storageBucket: 'reddit-clone-b5636.firebasestorage.app',
    measurementId: 'G-B4SGTQ554Q',
  );

}